sites:
  -
    title: 刘典的博客
    link: 'http://blog.sina.com.cn/ld2254432'
  -
    title: 'Abbey''s Blog'
    link: 'http://abbeychenxi.net/'
  -
    title: XiaoleiTech
    link: 'http://xiaolei.tech/'
  -
    title: 'Giraffe''s Home'
    link: 'https://yemengying.com/'
  -
    title: 'ScienJus''s Blog'
    link: 'http://www.scienjus.com'
  -
    title: 流浪小猫的博客
    link: 'http://blog.xcatliu.com'
  -
    title: 且听书吟
    link: 'https://yufan.me'
  -
    title: 'crossoverJie''s Blog'
    link: 'https://crossoverjie.top'
