absolute_urls: false
timezone: Asia/Shanghai
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
force_ssl: false
languages:
  include_default_lang: true
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
home:
  alias: /posts
  hide_in_urls: false
pages:
  theme: antimatter
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: 'Y-m-d H:i'
    short: 'd-m-y G:i'
    long: 'D, d M Y G:i:s'
  publish_dates: true
  process:
    markdown: true
    twig: false
  twig_first: false
  events:
    page: true
    twig: true
  markdown:
    extra: false
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  expires: 604800
  last_modified: false
  etag: false
  vary_accept_encoding: false
  redirect_default_route: false
  redirect_default_code: '301'
  redirect_trailing_slash: false
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  frontmatter:
    process_twig: false
    ignore_fields:
      - form
  markdown_extra: false
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: g
  lifetime: 604800
  gzip: false
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  umask_fix: false
assets:
  css_pipeline: true
  css_pipeline_include_externals: false
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: true
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: true
  js_minify: true
  enable_asset_timestamp: true
  collections:
    jquery: 'https://cdn.bootcss.com/jquery/2.1.0/jquery.min.js'
    font-awesome: 'https://cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.min.css'
errors:
  display: false
  log: true
debugger:
  enabled: false
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 85
  cache_all: false
  cache_perms: '0755'
  debug: false
media:
  enable_media_timestamp: false
  upload_limit: 0
session:
  enabled: true
  timeout: 1800
  name: grav-site
  secure: false
  httponly: true
gpm:
  releases: stable
